### PR TITLE
Each extension can be set up with a different extension

### PR DESCRIPTION
**Pull request by jagoPG**
Allows the possibility to define a concrete version of the AMP extension. Currently, **amp-mustache** version is 0.2, and most of the other extensions are 0.1.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

### CODE REVIEW

**Comment by benatespina** [comment]
Looks great but take in account that with your PR `amp-sticky-ad` component won't work because it's an exception that it needs **1.0** to work.

**Comment by benatespina** [comment]
@jagoPG I was thinking...
What about if we put version number explicitly in every component instead of `''`?

At the end, with the current proposal we need always key/value so, if we put the version in the array itself we can simplify the logic in the bottom of the file.

**Comment by benatespina** [comment]
@jagoPG Cool!! Merged!! 👍 Try to test in some project with dev-master and if it's ok, I'll tag the v0.2.0 ;)

**Comment by jagoPG** [comment]
> @jagoPG Cool!! Merged!! 👍 Try to test in some project with dev-master and if it's ok, I'll tag the v0.2.0 ;)

I confirm that it's working correctly in production environment. No errors found with Chrome's AMP validator plugin  :)

**Pull request merged**
